-- creates a database and table if it doesnot exist 
-- with unique, autogenerated primary key

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE cities (
	id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY,
	state_id INT NOT NULL FOREIGN KEY,
	name VARCHAR(256) NOT NULL
	FOREIGN KEY(state_id) References hbtn_0d_usa.states(id)
	);
